---
  - name: Pull Docker image
    docker_image:
      name: buffstyles/otus-reddit:1.0
      source: pull
    tags: deploy

  - name: Run otus-reddit container
    docker_container:
      name: reddit
      image: buffstyles/otus-reddit:1.0
      state: started
      restart_policy: always
      ports:
        - "9292:9292"
    tags: deploy
