---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentd.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fluentd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fluentd.name }}
    spec:
      serviceAccount: {{ .Values.fluentd.name }}
      serviceAccountName: {{ .Values.fluentd.name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.elasticsearch.name | quote }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.elasticsearch.service.port | quote }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
        resources:
          limits:
            memory: {{ .Values.fluentd.resources.limits.memory }}
          requests:
            cpu: {{ .Values.fluentd.resources.requests.cpu }}
            memory: {{ .Values.fluentd.resources.requests.memory }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: {{ .Values.fluentd.dockerContainersPath }}
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: {{ .Values.fluentd.dockerContainersPath }}
