---
  - name: Initialize the k8s cluster
    command: kubeadm init --apiserver-cert-extra-sans="{{ ansible_host }}" --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint="{{ ansible_host }}" --pod-network-cidr="{{ pod_network_cidr }}"

  - name: Setup kubeconfig for user
    command: "{{ item }}"
    with_items:
     - "mkdir -p /home/{{ deploy_user }}/.kube"
     - "cp -i /etc/kubernetes/admin.conf /home/{{ deploy_user }}/.kube/config"
     - "chown {{ deploy_user }}:{{ deploy_user }} /home/{{ deploy_user }}/.kube/config"

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command.txt"
