---
  - name: Create folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - /srv/gitlab/config
      - /srv/gitlab/logs
      - /srv/gitlab/data

  - name: Pull Gitlab docker image
    docker_image:
      name: gitlab/gitlab-ce:latest
      source: pull

  - name: Run Gitlab container
    docker_container:
      name: gitlab-ce
      image: gitlab/gitlab-ce:latest
      state: started
      restart_policy: always
      hostname: "{{ ansible_host }}"
      detach: yes
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
      volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
