FROM alpine:3.14.0

ENV APP_HOME /app

WORKDIR $APP_HOME

COPY . $APP_HOME

RUN apk update \
    && apk add --no-cache ruby ruby-rdoc ruby-bundler build-base ruby-dev\
    && gem install bundler:1.17.2 \
    && bundle install \
    && gem uninstall bundler:1.17.2 \
    && gem cleanup \
    && apk del build-base ruby-dev\
    && rm -rf $APP_HOME/Gemfile* \
              /usr/lib/ruby/gems/*/cache/*

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
