version: '3'
services:

  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"

networks:

  front_net:
    # name: front_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          # gateway: 10.0.1.1

  back_net:
    # name: back_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
          # gateway: 10.0.2.1
