version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    #build: ./ui
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net

  post:
    #build: ./post-py
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - front_net
      - back_net

  comment:
    #build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net

volumes:

  post_db:


networks:

  front_net:
   # name: front_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
         # gateway: 10.0.1.1

  back_net:
   # name: back_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
         # gateway: 10.0.2.1
