{
 "title": "Telegraf metrics",
 "description": "Telegraf metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "docker_n_containers" }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Stopped containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "Paused containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "docker_n_containers_paused" }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "avg(docker_container_cpu_usage_percent{host =~ \"$server$\"}) by (container_image)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{container_image}}",
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_cpu\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "RAM usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "avg(docker_container_mem_usage_percent{host=~ \"$server$\"}) by (container_image)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{container_image}}",
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  }
 ]
}