{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Env",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ui_request_count{kubernetes_namespace=~\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\",kubernetes_namespace=~\"$kubernetes_namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Response Time 95%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket{kubernetes_namespace=~\"$kubernetes_namespace\"}[5m])) by (le))"
    }
   ]
  }
 ]
}