---
  - name: Copy Calico manifest
    template:
      src: calico.yaml.j2
      dest: "/home/{{ deploy_user }}/calico.yaml"

  - name: Apply Calico manifest
    command: kubectl apply -f calico.yaml
