---
    - name: Update system, install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
       - apt-transport-https
       - ca-certificates
       - software-properties-common
       - python3-pip
       - python3-setuptools
       - virtualenv

    - name: Add apt key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt key for k8s
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: Add k8s repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker

    - name: Install k8s
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - kubeadm
        - kubectl
        - kubelet
        - docker-ce

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes

    - name: Install Docker SDK
      pip:
        name: docker

    - name: Config Docker Engine
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      notify: restart docker

    - name: Create a directory if it does not exist
      file:
        path: /etc/NetworkManager/conf.d
        state: directory
        mode: '0755'

    - name: Config NetworkManager
      template:
        src: calico.conf.j2
        dest: /etc/NetworkManager/conf.d/calico.conf
        owner: root
        group: root
