groups:
  - name: alert.rules

    rules:

    - alert: InstanceDown
      expr: up == 0
      for: 30s
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: ResponseTimeMoreThen95Percent
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[1m])) by (le)) > 0.1
      for: 1m
      labels:
        severety: warning
      annotations:
        description: 'HTTP Response time more then before'
        summary: 'HTTP Response time too high'
