---
  - name: Pull Gitlab-Runner docker image
    docker_image:
      name: gitlab/gitlab-runner:latest
      source: pull

  - name: Run Gitlab-Runner container
    docker_container:
      name: "{{ runner_name }}-{{ item }}"
      image: gitlab/gitlab-runner:latest
      state: started
      restart_policy: always
      detach: yes
      volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    with_sequence: count='{{ count }}'
    notify: run register command
