apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: post-endpoints
  labels:
    app: reddit
    release: prometheus
spec:
  selector:
    matchLabels:
      app: reddit
      component: post
  endpoints:
  - port: post
