FROM telegraf:1.19.0

COPY telegraf.conf /etc/telegraf/telegraf.conf

ENV HOST_ETC=/hostfs/etc
ENV HOST_PROC=/hostfs/proc
ENV HOST_SYS=/hostfs/sys
ENV HOST_VAR=/hostfs/var
ENV HOST_RUN=/hostfs/run
ENV HOST_MOUNT_PREFIX=/hostfs
