---
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
       - apt-transport-https
       - ca-certificates
       - software-properties-common
       - python3-pip
       - python3-setuptools
       - virtualenv
      tags: install

    - name: Add apt key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker
      tags: install

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes
      tags: install

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes
      tags: install

    - name: Install Docker SDK
      pip:
        name: docker
       # executable: pip3
      tags: install
